### ISSUE TITLE
docker-compose create named network

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/docker-existdb#57]
Small adjustment to docker compose

```
networks:
  www:
    name: www
    driver: bridge
```

Naming network allows multiple eXist instances to be attached to same network.
i.e. new IP address is assign, so you don't have to stop your existing eXistdb running container.
Found this handy when developing newBase60 lib, 
which uses a totally ephemeral container (no volume binds) for developing the lib

example of attaching to existing network ( note port number )

```
version: '3.4'
services:
  exDev-newBase60:
    image: $DOCKER_IMAGE:$DOCKER_TAG
    container_name: eXdev
    ports:
      - 8282:8080
```

docker-compose override 
To be used locally (not on travis)

```
version: '3.4'
networks:
  default:
    external:
      name: www
```
